# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	minecraft_version=1.21.1
	yarn_mappings=1.21.1+build.3
	loader_version=0.16.5

# Mod Properties
	mod_version = b1.1
	maven_group = dev.lvstrng
	archives_base_name = argon

# Dependencies
	fabric_version=0.108.0+1.21.1
